= bundler-audit-image
Otto Group Solution Provider (OSP) GmbH

Docker image for Ruby gem build-audit

== Initializing

For local development checkout the source code:

[source,bash]
----
cd <my_path> <1>
git clone <project> <2>
----
<1> Go to a local path of your choice
<2> Clone git project with clone address from github repository

== Usage

Check all gemfile lock files of your application by running the docker container.

Run the docker container mounting the volume with your gemfile lock files into
`/usr/src/app`.

[source,bash]
----
docker run --rm -v /path/to/your/app:/usr/src/app \
  movex/bundler-audit-image:latest
----

Or directly from directory with gemfiles

[source,bash]
----
docker run --rm -v "${PWD}":/usr/src/app \
  movex/bundler-audit-image:latest
----

The lock files may be contained in sub directories.

The default lock file pattern is `Gemfile*.lock`.
If the lock file matches a different name pattern use environment variable
`GEMFILE_LOCK_PATTERN` to provide that name pattern.
The pattern may contain asterisks.

[source,bash]
----
PATH_TO_APP=/path/to/your/app
GEMFILE_LOCK_PATTERN=GemfileWithSpecialPattern*.lock
docker run --rm -v ${PATH_TO_APP}:/usr/src/app \
  -e GEMFILE_LOCK_PATTERN=${GEMFILE_LOCK_PATTERN} \
  movex/bundler-audit-image:master_latest
----

== References

https://github.com/rubysec/bundler-audit
